// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnwbnT3HgTpo4cQHgs-FPT_d8kHYoZiy8',
    appId: '1:166553281324:web:497cff4774c38da5928289',
    messagingSenderId: '166553281324',
    projectId: 'goribli',
    authDomain: 'goribli.firebaseapp.com',
    storageBucket: 'goribli.firebasestorage.app',
    measurementId: 'G-BE9TSQ1M4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB985D-TKYNSGSUJ1RukNxASjzPdI-eiMI',
    appId: '1:166553281324:android:4692697295316c2a928289',
    messagingSenderId: '166553281324',
    projectId: 'goribli',
    storageBucket: 'goribli.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvhiMtERWo9v18ees8n-O3IdkwvOBHexE',
    appId: '1:166553281324:ios:6aff786a2ddecb85928289',
    messagingSenderId: '166553281324',
    projectId: 'goribli',
    storageBucket: 'goribli.firebasestorage.app',
    iosBundleId: 'com.appibrium.goribliStudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvhiMtERWo9v18ees8n-O3IdkwvOBHexE',
    appId: '1:166553281324:ios:6aff786a2ddecb85928289',
    messagingSenderId: '166553281324',
    projectId: 'goribli',
    storageBucket: 'goribli.firebasestorage.app',
    iosBundleId: 'com.appibrium.goribliStudio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnwbnT3HgTpo4cQHgs-FPT_d8kHYoZiy8',
    appId: '1:166553281324:web:03ef2a6715c5b0fb928289',
    messagingSenderId: '166553281324',
    projectId: 'goribli',
    authDomain: 'goribli.firebaseapp.com',
    storageBucket: 'goribli.firebasestorage.app',
    measurementId: 'G-Z5DE7W5LZ5',
  );
}
